### ISSUE TITLE
Bug 18174 - incorrect values in state.center

### ISSUE THREAD

**Issue by gmbecker** [r-devel/bug-bbq#22]
https://bugs.r-project.org/show_bug.cgi?id=18174

Behavior is as documented/expected, per R-core, but a patch to the documentation is desired built around the example @mmaechler posted in bugzilla.

Remember, we are treating Bugzilla as read-only for this event so discussion and engagement should happen here and only later be consolodated and moved to bugzilla.

**Comment by mmaechler** [comment]
well, no patch needed.  I should've been clearer in  https://bugs.r-project.org/show_bug.cgi?id=18174#c4
The R code I show is already ready to be commited (in my svn checkout of R-devel), but it needs verification / comments:
- please find a "documented"/"validated" set of (longitude/latitude) coordinates for Alaska and Hawaii
- possibly find a map drawing package (I used `{maps}`, with "states" boundaries already in the R code, but that does not contain AL & HI) which allows to draw AL & HI  *and* add an (x,y)  "point" to the plot.

**Comment by HayesJohnD** [comment]
Note the [USGS ](https://pubs.usgs.gov/gip/Elevations-Distances/elvadist.html#Geographic%20Centers) disclaimer below:

"Because there is no generally accepted definition of a geographic center and no completely satisfactory method of determining it, there may be as many geographic centers of a State or county as there are definitions of the term."

**Comment by mmaechler** [comment]
Thank you for the pointer, John (@HayesJohnD).  I've used their coordinates now, and also added their URL in the comment.
Committed to the R sources and hence closing.
